#!/usr/bin/env python3
"""Generates the website's brand assets from the SAME constants that draw the
store icon (tool/make_icons.py), so the mark on the site and the icon in the
store cannot drift apart.

Writes, relative to site/:
  src/components/Mark.astro   the mark as inline SVG (an Astro component)
  public/favicon.svg          the mark on its cream ground, rounded
  public/og.png               1200x630 Open Graph image
  public/apple-touch-icon.png 180x180 from the 1024 store icon

`--check` regenerates into memory and exits 1 if any committed file differs.
"""
from __future__ import annotations

import importlib.util
import io
import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

SITE = pathlib.Path(__file__).resolve().parent.parent
ROOT = SITE.parent

spec = importlib.util.spec_from_file_location("make_icons", ROOT / "tool" / "make_icons.py")
make_icons = importlib.util.module_from_spec(spec)
spec.loader.exec_module(make_icons)

G = make_icons._GEOMETRY
ART = make_icons.ARTBOARD
V = make_icons.VARIANTS["3b"]

W, H = G["capsule_w"], G["capsule_h"]
TOP = ART - G["bottom"] - H
LEFT = (ART - W) / 2
PIVOT = (ART / 2, TOP + G["pivot_y_fraction"] * H)
ROT = G["rotation_deg"]


def _num(x: float) -> str:
    s = f"{x:.3f}".rstrip("0").rstrip(".")
    return s if s else "0"


def _capsule_group(angle: float, top: str, bottom: str, clip_id: str) -> str:
    # Split lengthwise into two flat colours, clipped to the capsule, then
    # rotated about the shared pivot. PIL rotates counter-clockwise for a
    # positive angle and make_icons passes -css_angle, so the SVG angle is the
    # css angle unchanged: back capsule -26, front +26.
    return (
        f'<g transform="rotate({_num(angle)} {_num(PIVOT[0])} {_num(PIVOT[1])})" clip-path="url(#{clip_id})">'
        f'<rect x="{_num(LEFT)}" y="{_num(TOP)}" width="{_num(W)}" height="{_num(H / 2)}" fill="{top}"/>'
        f'<rect x="{_num(LEFT)}" y="{_num(TOP + H / 2)}" width="{_num(W)}" height="{_num(H / 2)}" fill="{bottom}"/>'
        f"</g>"
    )


def mark_body(clip_id: str) -> str:
    clip = (
        f'<clipPath id="{clip_id}"><rect x="{_num(LEFT)}" y="{_num(TOP)}" '
        f'width="{_num(W)}" height="{_num(H)}" rx="{_num(W / 2)}"/></clipPath>'
    )
    back = _capsule_group(-ROT, *V["back_capsule"], clip_id)
    front = _capsule_group(+ROT, *V["front_capsule"], clip_id)
    return f"<defs>{clip}</defs>{back}{front}"


def mark_astro() -> str:
    # Written as one explicit f-string rather than the `.replace` chain: the
    # body template is built with the LITERAL JS placeholder "${id}" as the
    # clip id (mark_body just formats whatever string it is given), so the
    # generated component clips two on-page instances to two distinct ids
    # without this script ever interpolating a real id itself.
    body_template = mark_body("${id}")
    return (
        "---\n"
        "// GENERATED by site/scripts/make_og.py from tool/make_icons.py. Do not edit;\n"
        "// run `npm run assets`. The geometry and colours are the store icon's own.\n"
        "interface Props { size?: number; title?: string }\n"
        f"const bodyFor = (id: string) => `{body_template}`;\n"
        "const { size = 28, title } = Astro.props;\n"
        "const clipId = `vm-cap-${Math.random().toString(36).slice(2, 8)}`;\n"
        "const body = bodyFor(clipId);\n"
        "---\n"
        f'<svg width={{size}} height={{size}} viewBox="0 0 {_num(ART)} {_num(ART)}" '
        'xmlns="http://www.w3.org/2000/svg" role={title ? "img" : undefined} '
        'aria-hidden={title ? undefined : "true"} focusable="false">\n'
        "  {title && <title>{title}</title>}\n"
        "  <Fragment set:html={body} />\n"
        "</svg>\n"
    )


def favicon_svg() -> str:
    r = ART * 0.22
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {_num(ART)} {_num(ART)}">'
        f'<rect width="{_num(ART)}" height="{_num(ART)}" rx="{_num(r)}" fill="{V["background"]}"/>'
        f'{mark_body("cap")}</svg>\n'
    )


def og_png() -> bytes:
    img = Image.new("RGB", (1200, 630), make_icons._rgb("#F7F6F3"))  # BqColors.paper
    mark = make_icons.draw_mark("3b", 360, ground=False)
    img.paste(mark, (96, 135), mark)
    font_path = str(ROOT / "assets" / "fonts" / "InstrumentSans[wdth,wght].ttf")
    name = ImageFont.truetype(font_path, 96)
    name.set_variation_by_axes([100, 600])
    line = ImageFont.truetype(font_path, 44)
    line.set_variation_by_axes([100, 500])
    d = ImageDraw.Draw(img)
    d.text((520, 200), "VitoMy", font=name, fill=make_icons._rgb("#17171B"))  # BqColors.ink
    d.text((520, 322), "Plan what you take.", font=line, fill=make_icons._rgb("#5C5C66"))
    d.text((520, 378), "See it laid out.", font=line, fill=make_icons._rgb("#5C5C66"))
    buf = io.BytesIO()
    img.save(buf, "PNG", optimize=True)
    return buf.getvalue()


def touch_icon_png() -> bytes:
    src = Image.open(ROOT / "store" / "icon" / "3b" / "appstore-icon-1024.png").convert("RGB")
    buf = io.BytesIO()
    src.resize((180, 180), Image.LANCZOS).save(buf, "PNG", optimize=True)
    return buf.getvalue()


OUTPUTS = {
    "src/components/Mark.astro": lambda: mark_astro().encode(),
    "public/favicon.svg": lambda: favicon_svg().encode(),
    "public/og.png": og_png,
    "public/apple-touch-icon.png": touch_icon_png,
}


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale: list[str] = []
    for rel, build in OUTPUTS.items():
        path = SITE / rel
        data = build()
        if check:
            if not path.exists() or path.read_bytes() != data:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(f"wrote {rel}")
    if stale:
        print("stale, run `npm run assets`: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
