/// Sync-ready Drift schema for VitoMy (DATA-02).
///
/// Every table mixes in [SyncColumns] (per D-17): TEXT UUID primary key,
/// createdAt/updatedAt true-UTC instants, and a nullable deletedAt for soft
/// deletes. No auto-increment integer keys and no hard deletes anywhere —
/// this is the persistence contract the future sync backend builds on.
///
/// DateTime storage is ISO-8601 text (see `build.yaml`:
/// `store_date_time_values_as_text: true`), so UTC values round-trip with
/// `isUtc == true` — preserving the UTC-midnight calendar identity that
/// date-only values rely on (D-13/D-18).
library;

import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

import '../domain/models.dart';

part 'database.g.dart';

/// Shared sync-ready columns mixed into every table (D-17).
///
/// No client-side defaults on purpose: every writer supplies explicit UTC
/// instants, keeping timestamps deterministic and test-controllable.
/// Repositories (plan 01-07) own timestamp assignment.
mixin SyncColumns on Table {
  /// TEXT UUID primary key — generated by repositories via `Uuid().v4()`,
  /// never by the database (no auto-increment, per DATA-02).
  TextColumn get id => text()();

  /// True UTC instant of row creation.
  DateTimeColumn get createdAt => dateTime()();

  /// True UTC instant of last modification.
  DateTimeColumn get updatedAt => dateTime()();

  /// Soft-delete marker: null while the row is live (DATA-02 — no hard
  /// deletes).
  DateTimeColumn get deletedAt => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

/// A supplement in the user's stack.
class Supplements extends Table with SyncColumns {
  TextColumn get name => text()();
  TextColumn get doseText => text()();

  /// ARGB color int used as the supplement's tag color in charts.
  IntColumn get colorValue => integer()();
  TextColumn get note => text()();
}

/// A dosing regimen for one supplement (cyclic on/off or one-time course).
class Regimens extends Table with SyncColumns {
  TextColumn get supplementId => text().references(Supplements, #id)();

  /// Stored as [RegimenKind.index].
  IntColumn get kind => intEnum<RegimenKind>()();

  /// Date-only value: always UTC midnight (`DateTime.utc(y, m, d)`).
  DateTimeColumn get startDate => dateTime()();

  /// Inclusive last active day for course regimens; null otherwise.
  /// Date-only value: always UTC midnight.
  DateTimeColumn get endDate => dateTime().nullable()();
  IntColumn get onDays => integer().withDefault(const Constant(0))();
  IntColumn get offDays => integer().withDefault(const Constant(0))();
  BoolColumn get paused => boolean().withDefault(const Constant(false))();
}

/// A time-of-day dose slot within a regimen.
class RegimenSlots extends Table with SyncColumns {
  TextColumn get regimenId => text().references(Regimens, #id)();

  /// Wall-clock time of day, minutes since midnight (0..1439).
  IntColumn get minutesFromMidnight => integer()();
  TextColumn get doseLabel => text()();
}

/// One materialized dose occurrence: a slot on a calendar day.
class IntakeLogs extends Table with SyncColumns {
  TextColumn get regimenId => text().references(Regimens, #id)();
  TextColumn get slotId => text().references(RegimenSlots, #id)();

  /// UTC-midnight calendar identity: always `DateTime.utc(y, m, d)`,
  /// never local midnight (D-18).
  DateTimeColumn get date => dateTime()();

  /// Stored as [DoseStatus.index] (D-18).
  IntColumn get status => intEnum<DoseStatus>()();

  /// (slotId, date) is unique so materialization with insert-or-ignore is
  /// idempotent — re-running "ensure today's rows exist" can never create
  /// duplicates or clobber recorded statuses (D-18).
  @override
  List<Set<Column>> get uniqueKeys => [
        {slotId, date},
      ];
}

@DriftDatabase(tables: [Supplements, Regimens, RegimenSlots, IntakeLogs])
class VitomyDb extends _$VitomyDb {
  /// Test-only constructor — pass `NativeDatabase.memory()`; never touches
  /// disk (D-19).
  VitomyDb.forTesting(super.executor);

  /// Opens the on-device database file `vitomy.sqlite`.
  ///
  /// D-21 / DATA-02: `driftDatabase(name:)` resolves the file into the
  /// platform app-documents directory — the iOS Documents directory (backed
  /// up by iCloud/iTunes by default) and Android internal app data (eligible
  /// for Auto Backup by default). The app must NEVER opt this file or itself
  /// out of OS backups: no `android:allowBackup="false"` in the manifest and
  /// no `NSURLIsExcludedFromBackupKey` on iOS. Backup inclusion is an OS
  /// default triggered by this file location — leave it alone.
  VitomyDb.open() : super(driftDatabase(name: 'vitomy'));

  @override
  int get schemaVersion => 1;
}
